platform :ios, '9.0'

use_frameworks!
pod 'RadioGroup', :path => '..'

# code quality scripts
def scripts
    script_phase :name => 'SwiftFormat', :execution_position => :before_compile, :script => 'if [ "Debug" = "${CONFIGURATION}" ]; then cd "${SRCROOT}/.."; swiftformat; fi'
    script_phase :name => 'SwiftLintAutocorrect', :execution_position => :before_compile, :script => 'if [ "Debug" = "${CONFIGURATION}" ]; then cd "${SRCROOT}/.."; swiftlint autocorrect; fi'
    script_phase :name => 'SwiftLint', :execution_position => :after_compile, :script => 'if [ "Debug" = "${CONFIGURATION}" ]; then cd "${SRCROOT}/.."; swiftlint; fi'
end

target 'RadioGroupDemo' do
    scripts
end

target 'RadioGroupDemoUITests' do
end
